### ISSUE TITLE
'struct GPIO_TypeDef' has no member named 'BSRR'

### ISSUE THREAD

**Issue by MHobert** [pkourany/SoftPWM#2]
Veryfing code using this library in Particle Build fails with this error:

```
SoftPWM/SoftPWM.cpp:132:56: error: 'struct GPIO_TypeDef' has no member named 'BSRR'
     PIN_MAP[_softpwm_channels[i].pin].gpio_peripheral->BSRR = PIN_MAP[_softpwm_channels[i].pin].gpio_pin
```

**Comment by pkourany** [comment]
Yup, this library was ported some time ago.  The new Core and Photon firmware release change things a lot so I will be updating the library.

**Comment by pkourany** [comment]
Web IDE library has been updated!

**Comment by MHobert** [comment]
Still getting this error message.  Why would this be?

**Comment by MHobert** [comment]
I am attempting to flash this code to a photon using the latest firmware: (0.4.6) but am still getting the error message,
