### ISSUE TITLE
'struct GPIO_TypeDef' has no member named 'BRR'

### ISSUE THREAD

**Issue by MHobert** [pkourany/SoftPWM#3]
Veryfing code using this library in Particle Build fails with this error:

```
SoftPWM/SoftPWM.cpp:138:56: error: 'struct GPIO_TypeDef' has no member named 'BRR'
     PIN_MAP[_softpwm_channels[i].pin].gpio_peripheral->BRR = PIN_MAP[_softpwm_channels[i].pin].gpio_pin
```

**Comment by pkourany** [comment]
Yup, this library was ported some time ago.  The new Core and Photon firmware release change things a lot so I will be updating the library.

**Comment by pkourany** [comment]
Web IDE library has been updated!

**Comment by MHobert** [comment]
Still getting the same error message. Why would this be?

Thanks.

**Comment by pkourany** [comment]
What platform (Core, Photon) and firmware version are you compiling to?

**Comment by MHobert** [comment]
Trying to compile to photon firmware version: Latest (0.4.6)Sent from Yahoo Mail for iPhoneOn Oct 3, 2015, 4:10:44 PM, Paul Kourany wrote:What platform (Core, Photon) and firmware version are you compiling to?
